### PR TITLE
Step 3 : Interactive Features

### PR DESCRIPTION
**Pull request by masangana**
### In this last step, we should :

- Create a new module for the status
- Check the change from checkbox
- Update completed value
- Clear all completed
- updated array of items in local storage

### CODE REVIEW

**Review by keneogu — CHANGES_REQUESTED** [review]
Hi @masangana, 

Good job so far!

- Linters are working
- Descriptive Pull request title and summary

There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes  ♻️

- [ ] The array is not stored.
- [ ] The updated array item should be stored in the localstorage.



_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

**Comment by masangana** [comment]
Hey @keneogu 
Thanks for you feedback. But it's not helpfull. You didn't give any information about what is not working correctly and I can't focus on the problem. Sometimes, everything can work correctly in the dev side. This is why give more information when review is important.

**Comment by masangana** [comment]
May be there som problem but i found no error from my side and everything is ok. i ask for another check

**Review by roshan-bajgain — CHANGES_REQUESTED** [review]
Hi @masangana, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
- PR has a good title and summary. ✔️

 ## Required Changes ♻️

- [ ] You have an error when running `npm start` due to package dependency`@popperjs/core` See the error below, kindly solve this issue and ask for another code review.
**Hint: _You may not face the same problem on your existing code on your device because of already installed node packages. So, either delete the `node_modules` directory or delete the existing project form your machine and clone form github_**
### Error
pp

- [ ] If you solve this issue then everything is working properly.


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by masangana** [comment]
### Hi @roshan-bajgain 

this problem is not to my side. You didn't install the package correctely

**Comment by masangana** [comment]
@roshan-bajgain 
I can't upload the node_module file.

**Comment by roshan-bajgain** [comment]
> ### Hi @roshan-bajgain
> this problem is not to my side. You didn't install the package correctely

Hello, @masangana the installation step is `npm install`, and all the dependencies should be installed while running this command but `@popperjs/core` is not there in the package file as it is creating the problem so kindly install @popperjs/core.

**Review by ahmetbozaci — APPROVED** [review]
# STATUS: APPROVED 🥳 🥳 🥳 



@masangana  ✋🏼 
#### Your project is great. 🎉 I approve of it. There is nothing else to say other than... it's time to merge it. You can submit this project on your dashboard.

___ 

### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Well done everything working fine. Only when clicking on the todo it is adding a new variable `status` there is no need for that. You have `completed` variable for that.
___

https://user-images.githubusercontent.com/38635158/171849684-cca9018e-ba16-4c4a-9a24-2906a42188ce.mp4



### Cheers and Happy coding! 💻 👏
aproved


___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._
___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_

[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

**Comment by masangana** [comment]
@roshan-bajgain 
The package node_modules/@popperjs/core is present. check on line 2075 inside packge-lock.json

**Pull request merged**
